name: 'jdk-wake'
author: 'Liwei Ma <liwei.ma@gmail.com>'
description: 'Invoke wake inside the alpine container'
inputs:
  command:
    description: |
      The command which will be executed by wake inside the workspace.
      By default, wake will simply type-check the build system.
    required: false
    default: '-x Unit'
  workspace:
    description: |
      The location (relative to the build directory) of the root of the wit
      workspace.  This should typically match wherever wit/actions/init ran.
    required: false
    default: .
  version:
    description: |
      The version of the environment-blockci-sifive docker image to use.  By
      default, the same version is used as the release tag of the action.
    required: false
    default: master

runs:
  using: 'composite'
  ## image: 'davidmlw/alpine:alpine-3.10'
  ## entrypoint: './entrypoint.sh'
  steps:
    - run: |
        set -xeuo pipefail
        docker run --rm \
          --device /dev/fuse --cap-add SYS_ADMIN --security-opt apparmor:unconfined \
          --volume="$GITHUB_WORKSPACE/${{ inputs.workspace }}:/mnt/workspace" --workdir="/mnt/workspace" \
          turbofive/alpine:jdk-3.10 \
          wake ${{ inputs.command }}
      shell: bash
