name: 'jdk-wake'
author: 'Liwei Ma <liwei.ma@sifive.com>'
description: 'Run a Wake with api-scala-sifive supported.'
inputs:
  arguments:
    description: |
      Wake actions. `wake --init .` has been executed and wake.db has bee generated.
    required: false
    default: ''
runs:
  using: 'composite'
  ## image: 'davidmlw/alpine:alpine-3.10'
  ## entrypoint: './entrypoint.sh'
  steps:
    - run: |
        set -xeuo pipefail
        docker run --rm \
          --device /dev/fuse --cap-add SYS_ADMIN --security-opt apparmor:unconfined \
          --volume="$GITHUB_WORKSPACE/${{ inputs.workspace }}:/mnt/workspace" --workdir="/mnt/workspace" \
          davidmlw/alpine:jdk-3.10 \
          wake ${{ inputs.command }}
      shell: bash
